alby/blog/urls.py
from django.urls import path

from . import views

app_name = "weblog"
urlpatterns = [
    path(
        "<int:year>/<str:month>/<int:day>/<slug>/",
        views.BlogDateDetailView.as_view(),
        name="entry",
    ),
    path(
        "<int:year>/<str:month>/<int:day>/",
        views.BlogDayArchiveView.as_view(),
        name="archive-day",
    ),
    path(
        "<int:year>/<str:month>/",
        views.BlogMonthArchiveView.as_view(),
        name="archive-month",
    ),
    path("<int:year>/", views.BlogYearArchiveView.as_view(), name="archive-year"),
    path("", views.BlogArchiveIndexView.as_view(), name="index"),
]

alby/blog/models.py
from urllib.parse import urlparse

from django.conf import settings
from django.core.cache import caches
from django.db import models
from django.test import RequestFactory
from django.utils import timezone
from django.utils.cache import _generate_cache_header_key
from django.utils.translation import gettext_lazy as _
from django_hosts.resolvers import reverse
from docutils.core import publish_parts
from markdown import markdown
from markdown.extensions.toc import TocExtension, slugify as _md_title_slugify

BLOG_DOCUTILS_SETTINGS = {
    "doctitle_xform": False,
    "initial_header_level": 3,
    "id_prefix": "s-",
    "raw_enabled": False,
    "file_insertion_enabled": False,
}
BLOG_DOCUTILS_SETTINGS.update(getattr(settings, "BLOG_DOCUTILS_SETTINGS", {}))


def _md_slugify(value, separator):
    # matches the `id_prefix` setting of BLOG_DOCUTILS_SETTINGS
    return "s" + separator + _md_title_slugify(value, separator)


class EntryQuerySet(models.QuerySet):
    def published(self):
        return self.active().filter(pub_date__lte=timezone.now())

    def active(self):
        return self.filter(is_active=True)


class ContentFormat(models.TextChoices):
    REST = "reST", "reStructuredText"
    HTML = "html", "Raw HTML"
    MARKDOWN = "md", "Markdown"

    @classmethod
    def to_html(cls, fmt, source):
        """
        Convert the given source from the given format to HTML
        """
        if not fmt or fmt == cls.HTML:
            return source
        if fmt == cls.REST:
            return publish_parts(
                source=source,
                writer_name="html",
                settings_overrides=BLOG_DOCUTILS_SETTINGS,
            )["fragment"]
        if fmt == cls.MARKDOWN:
            return markdown(
                source,
                output_format="html",
                extensions=[
                    # baselevel matches `initial_header_level` from BLOG_DOCUTILS_SETTINGS
                    TocExtension(baselevel=3, slugify=_md_slugify),
                ],
            )
        raise ValueError(f"Unsupported format {fmt}")


class Entry(models.Model):
    headline = models.CharField(max_length=200)
    slug = models.SlugField(unique_for_date="pub_date")
    is_active = models.BooleanField(
        help_text=_(
            "Tick to make this entry live (see also the publication date). "
            "Note that administrators (like yourself) are allowed to preview "
            "inactive entries whereas the general public aren't."
        ),
        default=False,
    )
    pub_date = models.DateTimeField(
        verbose_name=_("Publication date"),
        help_text=_(
            "For an entry to be published, it must be active and its "
            "publication date must be in the past."
        ),
    )
    content_format = models.CharField(choices=ContentFormat, max_length=50)
    summary = models.TextField()
    summary_html = models.TextField()
    body = models.TextField()
    body_html = models.TextField()
    author = models.CharField(max_length=100)

    objects = EntryQuerySet.as_manager()

    class Meta:
        db_table = "blog_entries"
        verbose_name_plural = "entries"
        ordering = ("-pub_date",)
        get_latest_by = "pub_date"

    def __str__(self):
        return self.headline

    def get_absolute_url(self):
        kwargs = {
            "year": self.pub_date.year,
            "month": self.pub_date.strftime("%b").lower(),
            "day": self.pub_date.strftime("%d").lower(),
            "slug": self.slug,
        }
        return reverse("weblog:entry", kwargs=kwargs)

    def is_published(self):
        """
        Return True if the entry is publicly accessible.
        """
        return self.is_active and self.pub_date <= timezone.now()

    is_published.boolean = True

    def save(self, *args, **kwargs):
        self.summary_html = ContentFormat.to_html(self.content_format, self.summary)
        self.body_html = ContentFormat.to_html(self.content_format, self.body)
        super().save(*args, **kwargs)
        self.invalidate_cached_entry()

    def invalidate_cached_entry(self):
        url = urlparse(self.get_absolute_url())
        rf = RequestFactory(
            SERVER_NAME=url.netloc,
            HTTP_X_FORWARDED_PROTOCOL=url.scheme,
        )
        is_secure = url.scheme == "https"
        request = rf.get(url.path, secure=is_secure)
        request.LANGUAGE_CODE = "en"
        cache = caches[settings.CACHE_MIDDLEWARE_ALIAS]
        cache_key = _generate_cache_header_key(
            settings.CACHE_MIDDLEWARE_KEY_PREFIX, request
        )
        cache.delete(cache_key)


class EventQuerySet(EntryQuerySet):
    def past(self):
        return self.filter(date__lte=timezone.now()).order_by("-date")

    def future(self):
        return self.filter(date__gte=timezone.now()).order_by("date")


class Event(models.Model):
    headline = models.CharField(max_length=200, null=False)
    external_url = models.URLField()
    date = models.DateField()
    location = models.CharField(max_length=100)
    is_active = models.BooleanField(
        help_text=_(
            "Tick to make this event live (see also the publication date). "
            "Note that administrators (like yourself) are allowed to preview "
            "inactive events whereas the general public aren't."
        ),
        default=False,
    )
    pub_date = models.DateTimeField(
        verbose_name=_("Publication date"),
        help_text=_(
            "For an event to be published, it must be active and its "
            "publication date must be in the past."
        ),
    )

    objects = EventQuerySet.as_manager()

    class Meta:
        ordering = ("-pub_date",)
        get_latest_by = "pub_date"

    def is_published(self):
        """
        Return True if the event is publicly accessible.
        """
        return self.is_active and self.pub_date <= timezone.now()

    is_published.boolean = True

alby/blog/views.py
from django.views.generic.dates import (
    ArchiveIndexView,
    DateDetailView,
    DayArchiveView,
    MonthArchiveView,
    YearArchiveView,
)

from .models import Entry, Event


class BlogViewMixin:
    date_field = "pub_date"
    paginate_by = 10

    def get_allow_future(self):
        return self.request.user.is_staff

    def get_queryset(self):
        if self.request.user.is_staff:
            return Entry.objects.all()
        else:
            return Entry.objects.published()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        events_queryset = Event.objects.future().published()

        context["events"] = events_queryset[:3]

        return context


class BlogArchiveIndexView(BlogViewMixin, ArchiveIndexView):
    pass


class BlogYearArchiveView(BlogViewMixin, YearArchiveView):
    make_object_list = True


class BlogMonthArchiveView(BlogViewMixin, MonthArchiveView):
    pass


class BlogDayArchiveView(BlogViewMixin, DayArchiveView):
    pass


class BlogDateDetailView(BlogViewMixin, DateDetailView):
    pass

alby/alby/templates/blog/blog_pagination.html
{% load i18n %}

{% if is_paginated %}
  <div class="pagination">
    <ul class="nav-pagination" role="navigation">
      {% if page_obj.has_previous %}
        <li><a rel="prev" class="previous" href="?page={{ page_obj.previous_page_number }}">
          <i class="icon icon-chevron-left"></i>
          <span class="visuallyhidden">{% translate "Previous" context "pagination" %}</span>
        </a></li>
      {% endif %}
      <span class="page-current">
        {% blocktranslate trimmed with page_num=page_obj.number pages=page_obj.paginator.num_pages %}
          Page {{ page_num }} of {{ pages }}
        {% endblocktranslate %}
      </span>
      {% if page_obj.has_next %}
        <li><a rel="next" class="next" href="?page={{ page_obj.next_page_number }}">
          <i class="icon icon-chevron-right"></i>
          <span class="visuallyhidden">{% translate "Next" context "pagination" %}</span>
        </a></li>
      {% endif %}
    </ul>
  </div>
{% endif %}

alby/alby/templates/blog/entry_archive.html
{% extends "base_weblog.html" %}

{% block content %}

  {% comment %}
    {# This is not implemented in backend yet #}
    <form action="#" class="form-input" role="search">
      <label class="visuallyhidden" for="news-search">Search:</label>
      <input type="text" name="news-search" id="news-search" placeholder="Search News" />
      <button type="submit">
        <i class="icon icon-search"></i>
        <span class="visuallyhidden">Search</span>
      </button>
    </form>
  {% endcomment %}

  <ul class="list-news">

    {% for object in latest %}
      {% include 'blog/news_summary.html' with object=object %}
    {% endfor %}

  </ul>

  {% include 'blog/blog_pagination.html' %}

{% endblock %}

alby/alby/templates/blog/entry_archive_day.html
{% extends "base_weblog.html" %}
{% load i18n %}

{% block title %}{{ day|date:"MONTH_DAY_FORMAT" }} | {% translate "Weblog" %}{% endblock %}

{% block og_title %}{% blocktranslate %}Django news: {{ day|date:"MONTH_DAY_FORMAT" }} archive{% endblocktranslate %}{% endblock %}

{% block content %}

  <h1>{% blocktranslate %}{{ day|date:"MONTH_DAY_FORMAT" }} archive{% endblocktranslate %}</h1>

  <ul class="list-news">

    {% for object in object_list %}
      {% include 'blog/news_summary.html' with object=object %}
    {% endfor %}

  </ul>

  {% include 'blog/blog_pagination.html' %}

{% endblock %}

alby/alby/templates/blog/entry_archive_month.html
{% extends "base_weblog.html" %}
{% load i18n %}

{% block title %}{{ month|date:"YEAR_MONTH_FORMAT" }} | {% translate "Weblog" %}{% endblock %}

{% block og_title %}{% blocktranslate %}Django news: {{ month|date:"YEAR_MONTH_FORMAT" }} archive{% endblocktranslate %}{% endblock %}

{% block content %}

  <h1>{% blocktranslate %}{{ month|date:"YEAR_MONTH_FORMAT" }} archive{% endblocktranslate %}</h1>

  <ul class="list-news">

    {% for object in object_list %}
      {% include 'blog/news_summary.html' with object=object %}
    {% endfor %}

  </ul>

  {% include 'blog/blog_pagination.html' %}

{% endblock %}

alby/alby/templates/blog/entry_archive_year.html
{% extends "base_weblog.html" %}
{% load i18n %}

{% block title %}{{ year|date:"Y" }} | {% translate "Weblog" %}{% endblock %}

{% block og_title %}{% blocktranslate with year=year|date:"Y" %}Django news: {{ year }} archive{% endblocktranslate %}{% endblock %}

{% block content %}

  <h1>{{ year|date:"Y" }} {% translate "archive" %}</h1>

  <ul class="list-news">

    {% for object in object_list %}
      {% include 'blog/news_summary.html' with object=object %}
    {% endfor %}

  </ul>

  {% include 'blog/blog_pagination.html' %}

{% endblock %}

alby/alby/templates/blog/entry_detail.html
{% extends "base_weblog.html" %}
{% load i18n %}

{% block title %}{{ object.headline|escape }} | Weblog{% endblock %}

{% block og_title %}{{ object.headline|safe }}{% endblock %}
{% block og_description %}{% blocktranslate trimmed with author=object.author pub_date=object.pub_date|date:"DATE_FORMAT" %}
    Posted by {{ author }} on {{ pub_date }}
{% endblocktranslate %}{% endblock %}

{% block content %}
    <h2>{{ object.headline|safe }}</h2>

    <span class="meta">{% blocktranslate trimmed with author=object.author pub_date=object.pub_date|date:"DATE_FORMAT" %}
        Posted by <strong>{{ author }}</strong> on {{ pub_date }} </span>
    {% endblocktranslate %}
        {{ object.body_html|safe }}
{% endblock %}

alby/alby/templates/blog/entry_snippet.html
<ul class="list-news">
    {% for e in entries %}
        {% include 'blog/news_summary.html' with object=e %}
    {% endfor %}
</ul>

alby/alby/templates/blog/month_links_snippet.html
{% load i18n %}
{% regroup dates by year as dates_by_year %}

<ul class="list-collapsing active">
  {% for month in dates_by_year %}
    <li id="year{{ month.grouper }}"{% if forloop.first %} class="active"{% endif %}>
      <h2><a href="{% url 'weblog:archive-year' month.grouper %}">{{ month.grouper }}</a> <i class="collapsing-icon icon icon-plus"></i></h2>
      <div class="collapsing-content">
        <ul class="list-links-small">
          {% for d in month.list %}
            <li><a href="{% language "en" %}{% url 'weblog:archive-month' d|date:"Y" d|date:"b" %}{% endlanguage %}">{{ d|date:"YEAR_MONTH_FORMAT" }}</a></li>
          {% endfor %}
        </ul>
        <p></p>
      </div>
    </li>
  {% endfor %}
</ul>

alby/alby/templates/blog/news_summary.html
{% load i18n %}

<li{% if not object.is_published %} class="unpublished"{% endif %}>
  <{{ header_tag|default:'h2' }}>
  <a href="{{ object.get_absolute_url }}">{{ object.headline|safe }}</a>
</{{ header_tag|default:'h2' }}>
{% if summary_first %}
  {{ object.summary_html|safe }}
{% endif %}
<span class="meta">
  {% blocktranslate trimmed with author=object.author pub_date=object.pub_date|date:"DATE_FORMAT" %}
    Posted by <strong>{{ author }}</strong> on {{ pub_date }}
  {% endblocktranslate %}
</span>
{% if not summary_first %}
  {{ object.summary_html|safe }}
{% endif %}
{% if not hide_readmore %}
  <a class="link-readmore" href="{{ object.get_absolute_url }}">
    {% translate "Read more" context "Following article summary" %}
  </a>
{% endif %}
</li>