alby/blog/urls.py
from django.urls import path

from . import views

app_name = "weblog"
urlpatterns = [
    path(
        "<int:year>/<str:month>/<int:day>/<slug>/",
        views.BlogDateDetailView.as_view(),
        name="entry",
    ),
    path(
        "<int:year>/<str:month>/<int:day>/",
        views.BlogDayArchiveView.as_view(),
        name="archive-day",
    ),
    path(
        "<int:year>/<str:month>/",
        views.BlogMonthArchiveView.as_view(),
        name="archive-month",
    ),
    path("<int:year>/", views.BlogYearArchiveView.as_view(), name="archive-year"),
    path("", views.BlogArchiveIndexView.as_view(), name="index"),
]

alby/contact/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .views import ContactFoundation

urlpatterns = [
    path("foundation/", ContactFoundation.as_view(), name="contact_foundation"),
    path(
        "sent/",
        TemplateView.as_view(template_name="contact/sent.html"),
        name="contact_form_sent",
    ),
]

alby/foundation/models.py
from decimal import Decimal

from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils.dateformat import format as date_format
from django.utils.translation import gettext_lazy as _
from djmoney.models.fields import MoneyField
from djmoney.settings import CURRENCIES
from docutils.core import publish_parts

from blog.models import BLOG_DOCUTILS_SETTINGS


class Office(models.Model):
    """
    An office held by a DSF Board member.

    """

    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name


class Term(models.Model):
    """
    A term in which DSF Board members served.

    """

    year = models.CharField(max_length=4, unique=True)

    def __str__(self):
        return self.year


class BoardMember(models.Model):
    """
    A DSF Board member.

    """

    account = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    office = models.ForeignKey(Office, related_name="holders", on_delete=models.CASCADE)
    term = models.ForeignKey(
        Term, related_name="board_members", on_delete=models.CASCADE
    )

    def __str__(self):
        return f"{self.account.get_full_name()} ({self.office} - {self.term.year})"


class NonBoardAttendee(models.Model):
    """
    A non-Board member attending a Board meeting.

    """

    name = models.CharField(max_length=255)
    role = models.CharField(max_length=100)

    class Meta:
        verbose_name = _("Non-board attendee")
        verbose_name_plural = _("Non-board attendees")

    def __str__(self):
        return f"{self.name} ({self.role})"


class Meeting(models.Model):
    """
    A meeting of the DSF Board.

    """

    date = models.DateField()
    title = models.CharField(max_length=255)
    slug = models.SlugField()
    leader = models.ForeignKey(
        BoardMember, related_name="meetings_led", on_delete=models.CASCADE
    )
    board_attendees = models.ManyToManyField(
        BoardMember, related_name="meetings_attended"
    )
    non_board_attendees = models.ManyToManyField(
        NonBoardAttendee, related_name="meetings_attended", blank=True
    )
    treasurer_balance = MoneyField(
        max_digits=10,
        decimal_places=2,
        default_currency="USD",
        default=Decimal("0.0"),
    )
    treasurer_report = models.TextField(blank=True)
    treasurer_report_html = models.TextField(editable=False)

    def __str__(self):
        return "{}, {}".format(self.title, date_format(self.date, "F j, Y"))

    def save(self, *args, **kwargs):
        if self.treasurer_report:
            self.treasurer_report_html = publish_parts(
                source=self.treasurer_report,
                writer_name="html",
                settings_overrides=BLOG_DOCUTILS_SETTINGS,
            )["fragment"]
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse(
            "foundation_meeting_detail",
            args=(),
            kwargs={
                "year": self.date.strftime("%Y"),
                "month": self.date.strftime("%b").lower(),
                "day": self.date.strftime("%d"),
                "slug": self.slug,
            },
        )


class ApprovedGrant(models.Model):
    """
    A grant approved by the DSF Board.

    """

    entity = models.CharField(max_length=255)
    amount = MoneyField(
        max_digits=10,
        decimal_places=2,
        default_currency="USD",
        default=Decimal("0.0"),
        currency_choices=[
            (c.code, c.name)
            for i, c in CURRENCIES.items()
            if c.code
            in {
                "USD",
                "EUR",
                "AUD",
                "NGN",
            }  # This set of currencies was extracted from current usage
        ],
    )
    approved_at = models.ForeignKey(
        Meeting, related_name="grants_approved", on_delete=models.CASCADE
    )

    class Meta:
        ordering = ("entity",)

    def __str__(self):
        return f"{self.entity}: {self.amount}"


class ApprovedIndividualMember(models.Model):
    """
    An individual DSF member approved by the Board.

    """

    name = models.CharField(max_length=255)
    approved_at = models.ForeignKey(
        Meeting, related_name="individual_members_approved", on_delete=models.CASCADE
    )

    def __str__(self):
        return self.name


class ApprovedCorporateMember(models.Model):
    """
    A corporate DSF member approved by the Board.

    """

    name = models.CharField(max_length=255)
    approved_at = models.ForeignKey(
        Meeting, related_name="corporate_members_approved", on_delete=models.CASCADE
    )

    def __str__(self):
        return self.name


class Business(models.Model):
    """
    Business of the DSF Board.

    """

    NEW = "new"
    ONGOING = "ongoing"

    TYPE_CHOICES = (
        (NEW, _("New")),
        (ONGOING, _("Ongoing")),
    )

    title = models.CharField(max_length=255)
    body = models.TextField()
    body_html = models.TextField(editable=False)
    business_type = models.CharField(max_length=25, choices=TYPE_CHOICES)
    meeting = models.ForeignKey(
        Meeting, related_name="business", on_delete=models.CASCADE
    )

    class Meta:
        ordering = ("title",)
        verbose_name_plural = _("Business")

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.body_html = publish_parts(
            source=self.body,
            writer_name="html",
            settings_overrides=BLOG_DOCUTILS_SETTINGS,
        )["fragment"]
        super().save(*args, **kwargs)


class ActionItem(models.Model):
    """
    A task to be completed by an attendee of a DSF Board meeting.

    """

    responsible = models.CharField(max_length=255)
    task = models.TextField()
    meeting = models.ForeignKey(
        Meeting, related_name="action_items", on_delete=models.CASCADE
    )

    def __str__(self):
        return self.task


class CoreAwardCohort(models.Model):
    """
    A cohort of individuals -- such as "Q1 2021" -- receiving the Django Core
    Developer title.
    """

    name = models.CharField(
        max_length=255,
        unique=True,
        help_text=_("Name for the group being inducted, e.g. 'Q1 2021'"),
    )
    description = models.TextField(blank=True)
    cohort_date = models.DateField(
        help_text=_("Date this cohort was approved by the DSF Board"),
    )

    def __str__(self):
        return self.name


class CoreAward(models.Model):
    """An individual person awarded the Django Core Developer title."""

    cohort = models.ForeignKey(
        CoreAwardCohort,
        related_name="recipients",
        on_delete=models.CASCADE,
    )
    recipient = models.CharField(
        help_text=_("Recipient's name"), max_length=1023, unique=True
    )
    link = models.URLField(
        blank=True,
        null=True,
        help_text=_("Optional link for this recipient"),
    )
    description = models.TextField(
        blank=True,
        help_text=_(
            "Optional one-paragraph description/bio of why this person "
            "received the award"
        ),
    )

    class Meta:
        ordering = ["recipient"]

    def __str__(self):
        return self.recipient

alby/contact/forms.py
import logging

import django
from django import forms
from django.conf import settings
from django.contrib.sites.models import Site
from django.utils.encoding import force_bytes
from django.utils.translation import gettext_lazy as _
from django_contact_form.forms import ContactForm
from django_recaptcha.fields import ReCaptchaField
from django_recaptcha.widgets import ReCaptchaV3
from pykismet3 import Akismet, AkismetServerError

logger = logging.getLogger(__name__)


class BaseContactForm(ContactForm):
    message_subject = forms.CharField(
        max_length=100,
        widget=forms.TextInput(
            attrs={"class": "required", "placeholder": _("Message subject")}
        ),
        label=_("Message subject"),
    )
    email = forms.EmailField(
        widget=forms.TextInput(attrs={"class": "required", "placeholder": _("E-mail")})
    )
    name = forms.CharField(
        widget=forms.TextInput(attrs={"class": "required", "placeholder": _("Name")})
    )
    body = forms.CharField(
        widget=forms.Textarea(
            attrs={"class": "required", "placeholder": _("Your message")}
        )
    )
    captcha = ReCaptchaField(widget=ReCaptchaV3)

    def subject(self):
        # Strip all linebreaks from the subject string.
        subject = "".join(self.cleaned_data["message_subject"].splitlines())
        return "[Contact form] " + subject

    def message(self):
        return "From: {name} <{email}>\n\n{body}".format(**self.cleaned_data)

    def clean_body(self):
        """
        Check spam against Akismet.

        Backported from django-contact-form pre-1.0; 1.0 dropped built-in
        Akismet support.
        """
        if "body" in self.cleaned_data and getattr(settings, "AKISMET_API_KEY", None):
            try:
                akismet_api = Akismet(
                    api_key=settings.AKISMET_API_KEY,
                    blog_url="http://%s/" % Site.objects.get_current().domain,
                    user_agent="Django {}.{}.{}".format(*django.VERSION),
                )

                akismet_data = {
                    "user_ip": self.request.META.get("REMOTE_ADDR", ""),
                    "user_agent": self.request.headers.get("user-agent", ""),
                    "referrer": self.request.headers.get("referer", ""),
                    "comment_content": force_bytes(self.cleaned_data["body"]),
                    "comment_author": self.cleaned_data.get("name", ""),
                    "comment_author_email": self.cleaned_data.get("email", ""),
                    "comment_type": "contact-form",
                }
                if getattr(settings, "AKISMET_TESTING", None):
                    # Adding test argument to the request in order to
                    # tell akismet that they should ignore the request
                    # so that test runs affect the heuristics
                    akismet_data["test"] = 1
                if akismet_api.check(akismet_data):
                    raise forms.ValidationError("Akismet thinks this message is spam")
            except AkismetServerError:
                logger.error("Akismet server error")
        return self.cleaned_data["body"]


class FoundationContactForm(BaseContactForm):
    recipient_list = ["dsf-board@googlegroups.com"]

alby/contact/views.py
from django.urls import reverse
from django_contact_form.views import ContactFormView

from .forms import FoundationContactForm


class ContactFoundation(ContactFormView):
    form_class = FoundationContactForm
    template_name = "contact/foundation.html"

    def get_success_url(self):
        return reverse("contact_form_sent")

alby/foundation/views.py
from django.views import generic

from . import models


class MeetingMixin:
    date_field = "date"
    model = models.Meeting


class MeetingArchiveIndex(MeetingMixin, generic.ArchiveIndexView):
    pass


class MeetingArchiveYear(MeetingMixin, generic.YearArchiveView):
    make_object_list = True


class MeetingArchiveMonth(MeetingMixin, generic.MonthArchiveView):
    pass


class MeetingArchiveDay(MeetingMixin, generic.DayArchiveView):
    pass


class MeetingDetail(MeetingMixin, generic.DateDetailView):
    context_object_name = "meeting"

    def get_queryset(self):
        return (
            super()
            .get_queryset()
            .select_related("leader")
            .prefetch_related(
                "grants_approved",
                "individual_members_approved",
                "corporate_members_approved",
                "business",
                "action_items",
                "board_attendees",
                "non_board_attendees",
            )
        )

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        meeting = context_data["object"]
        context_data["ongoing_business"] = meeting.business.filter(
            business_type=models.Business.ONGOING
        )
        context_data["new_business"] = meeting.business.filter(
            business_type=models.Business.NEW
        )
        return context_data


class CoreDevelopers(generic.ListView):
    queryset = models.CoreAwardCohort.objects.prefetch_related("recipients").order_by(
        "-cohort_date"
    )

alby/alby/templates/contact/coc.html
{% extends "base_3col.html" %}
{% load i18n %}

{% block title %}{% translate "Django Code of Conduct Feedback" %}{% endblock %}

{% block content %}
    <h1>{% translate "Django Code of Conduct Feedback" %}</h1>
    {% include "contact/coc_form.html" %}
{% endblock %}

alby/alby/templates/contact/coc_form.html
{% load i18n %}
<form action="{% url "contact_coc" %}" method="post" accept-charset="utf-8" class="wide">
  {% csrf_token %}

{# hardcoding inputs because they'll be included on the CoC page itself #}
  <p>
    <label for="id_name">{% translate "Your name (optional):" %}</label>
    {% if form.name.errors %}<p class="errors">{{ form.name.errors.as_text }}</p>{% endif %}
    <input id="id_name" class="required" type="text" name="name">
  </p>
  <p>
    <label for="id_email">{% translate "Your email address (optional):" %}</label>
    {% if form.email.errors %}<p class="errors">{{ form.email.errors.as_text }}</p>{% endif %}
    <input id="id_email" class="required" type="text" name="email">
  </p>
  <p>
    <label for="id_body">{% translate "Your message:" %}</label>
    {% if form.body.errors %}<p class="errors">{{ form.body.errors.as_text }}</p>{% endif %}
    <textarea id="id_body" class="required" rows="10" name="body" cols="40"></textarea>
  </p>
  <p class="submit"><input type="submit" value="{% translate "Send &rarr;" %}"></p>

</form>

alby/alby/templates/contact/foundation.html
{% extends "base_foundation.html" %}
{% load i18n %}

{% block title %}{% translate "Contact the Django Software Foundation" %}{% endblock %}

{% block content %}
  <h1>{% translate "Contact the Django Software Foundation" %}</h1>
  <p>
    {% blocktranslate trimmed %}
      This contact form is for the Django Software Foundation - the legal and
      fundraising arm of the Django project.
    {% endblocktranslate %}
  </p>
  <p>
    {% blocktranslate trimmed %}
      If you want to report a bug, feature request, or documentation issue in Django,
      use the <a href="https://code.djangoproject.com">ticket tracker</a>.
    {% endblocktranslate %}
  </p>
  <p>
    {% blocktranslate trimmed %}
      If you want to report a problem with this website, use the
      <a href="https://github.com/django/djangoproject.com">GitHub repo</a>.
    {% endblocktranslate %}
  </p>
  <p>
    {% blocktranslate trimmed %}
      If you've got questions about how to use Django, use the
      <a href="https://forum.djangoproject.com">Django Forum</a>.
    {% endblocktranslate %}
  </p>
  <form action="." method="post" accept-charset="utf-8" class="form-input">
    {% csrf_token %}
    <p>
      {% if form.name.errors %}<p class="errors">{{ form.name.errors.as_text }}</p>{% endif %}
      {{ form.name }}
    </p>
    <p class="form-email">
      {% if form.email.errors %}<p class="errors">{{ form.email.errors.as_text }}</p>{% endif %}
      {{ form.email }}
    </p>
    <p>
      {% if form.message_subject.errors %}<p class="errors">{{ form.message_subject.errors.as_text }}</p>{% endif %}
      {{ form.message_subject }}
    </p>
    <p>
      {% if form.body.errors %}<p class="errors">{{ form.body.errors.as_text }}</p>{% endif %}
      {{ form.body }}
    </p>
    <p>{{ form.captcha }}</p>
    <p class="submit"><input type="submit" class="cta" value="{% translate "Send &rarr;" %}"></p>
  </form>
{% endblock %}

alby/alby/templates/contact/sent.html
{% extends "base_foundation.html" %}
{% load i18n %}

{% block title %}{% translate "Message sent" %}{% endblock %}

{% block content %}
  <h1>{% translate "Message sent" %}</h1>
  <h2 class="deck">{% translate "Your message has been sent; thanks!" %}</h2>
  <p>
    {% blocktranslate trimmed %}
      Your mail <em>will</em> be read by a real, live human being. We can't
      guarantee when or whether you'll get a reply, but your message
      <em>will</em> be read, generally within the next couple of days.
    {% endblocktranslate %}
  </p>
  <p>
    {% blocktranslate trimmed %}
      If you're expecting a reply and don't get one, please feel free
      to send a reminder. Please wait a few days, however, unless
      it's an emergency.
    {% endblocktranslate %}
  </p>
{% endblock %}